'use client';

import { useMemo, useState } from 'react';
import Image from 'next/image';
import {
  User,
  Printer,
  ShieldCheck,
  Mail,
  Calendar,
  Briefcase,
  Sparkles,
  RotateCw,
} from 'lucide-react';
import { SectionCard } from '@/components/dashboard/SectionCard';
import { Badge } from '@/components/dashboard/Badge';
import { Button } from '@/components/ui/Button';
import { useAuth } from '@/hooks/useAuth';
import { LoadingState } from '@/components/dashboard/PageState';
import { QRCodeSVG } from 'qrcode.react';
import { OFFICE_PHONE_DISPLAY } from '@/lib/institute-contact';

/* ── Barcode Generator for Teacher ID ── */
function TeacherBarcode({ value }: { value: string }) {
  const seed = value.split('').map((c) => c.charCodeAt(0));
  type Bar = { x: number; w: number; black: boolean };
  const bars: Bar[] = [];
  let cursor = 0;
  let i = 0;
  const targetWidth = 220;

  while (cursor < targetWidth) {
    const w = ((seed[i % seed.length] + i * 2) % 3) + 1.2;
    bars.push({ x: cursor, w: Math.min(w * 1.8, targetWidth - cursor), black: i % 2 === 0 });
    cursor += w * 1.8;
    i++;
  }

  return (
    <div className="flex flex-col items-center gap-1">
      <svg
        width="220"
        height="38"
        viewBox="0 0 220 38"
        xmlns="http://www.w3.org/2000/svg"
        className="w-full max-w-[220px] h-9"
      >
        {bars.map((b, idx) =>
          b.black ? (
            <rect key={idx} x={b.x} y={0} width={b.w} height={38} fill="#0F172A" />
          ) : null
        )}
      </svg>
      <span className="font-mono text-[9px] tracking-[0.25em] text-[#1A2B4A] font-bold">
        * {value} *
      </span>
    </div>
  );
}

/* ── Autogenerated Director Signature ── */
function DirectorSignature() {
  return (
    <svg viewBox="0 0 140 40" xmlns="http://www.w3.org/2000/svg" className="w-32 h-10">
      <path
        d="M8 26 C22 10, 38 8, 52 20 C64 30, 72 12, 86 16 C98 20, 110 32, 122 22 C128 16, 134 22, 138 26"
        fill="none"
        stroke="#1E3A8A"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M10 32 C40 31, 85 31, 134 33"
        fill="none"
        stroke="#1E3A8A"
        strokeWidth="0.8"
        strokeLinecap="round"
      />
    </svg>
  );
}

function ProfileItem({ label, value, icon }: { label: string; value: string; icon?: React.ReactNode }) {
  return (
    <div className="flex items-start gap-2.5">
      {icon && <div className="mt-0.5 text-[#1295D8] shrink-0">{icon}</div>}
      <div className="min-w-0">
        <p className="text-xs font-semibold uppercase tracking-wider text-[#718096]">{label}</p>
        <p className="mt-0.5 text-sm font-semibold text-[#1A2B4A]">{value}</p>
      </div>
    </div>
  );
}

const ROLE_LABELS: Record<string, string> = {
  teacher: 'Faculty Member',
  admin: 'Administrator',
  accountant: 'Accountant',
};

export default function TeacherProfilePage() {
  const { user, loading } = useAuth();
  const [activeTab, setActiveTab] = useState<'both' | 'front' | 'back'>('both');
  const [isFlipped, setIsFlipped] = useState(false);

  // Identity comes from the signed-in account. Employment/personal details
  // (joining date, blood group, address…) are not stored yet, so they are not shown.
  const teacher = useMemo(() => {
    const role = user?.role ?? 'teacher';
    return {
      fullName: user?.fullName || user?.email || 'Faculty Member',
      email: user?.email || '—',
      employeeId: user ? `GK-${role === 'teacher' ? 'FAC' : role.slice(0, 3).toUpperCase()}-${user.id.replace(/-/g, '').slice(0, 6).toUpperCase()}` : '—',
      designation: ROLE_LABELS[role] ?? 'Faculty Member',
    };
  }, [user]);

  const handlePrint = () => {
    window.print();
  };

  if (loading && !user) return <LoadingState label="Loading profile…" />;

  return (
    <div className="space-y-8">
      {/* ── Page Header (Hidden on Print) ── */}
      <div className="flex flex-wrap items-center justify-between gap-4 print:hidden">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-3xl font-extrabold tracking-tight text-[#1A2B4A]">
              Faculty Profile &amp; ID Card
            </h1>
            <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-0.5 text-xs font-semibold text-[#1295D8] border border-blue-200">
              <Sparkles size={12} /> Faculty Member
            </span>
          </div>
          <p className="mt-1 text-sm text-[#4A5568]">
            Teacher employment details, qualifications, assigned subjects, and official faculty identity badge.
          </p>
        </div>

        <Button
          type="button"
          onClick={handlePrint}
          className="gap-2 bg-gradient-to-r from-[#1295D8] to-[#2E5EAA] text-white shadow-md hover:shadow-lg transition-all"
        >
          <Printer size={16} /> Print Faculty ID Card (PDF)
        </Button>
      </div>

      {/* ════════════════════════════════════════════════════════════════
          TEACHER IDENTITY CARD SHOWCASE (Interactive & Printable)
          ════════════════════════════════════════════════════════════════ */}
      <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm print:p-0 print:border-none print:shadow-none print:m-0">
        {/* Showcase Header Controls (Hidden on Print) */}
        <div className="mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-gray-100 pb-4 print:hidden">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-[#1A2B4A]">Faculty ID Card Preview</h2>
            <Badge tone="blue">{teacher.employeeId}</Badge>
            <Badge tone="green">Active Staff</Badge>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <div className="inline-flex rounded-lg border border-gray-200 bg-gray-50 p-1 text-xs font-semibold">
              <button
                type="button"
                onClick={() => {
                  setActiveTab('both');
                  setIsFlipped(false);
                }}
                className={`rounded-md px-3 py-1.5 transition-colors ${
                  activeTab === 'both' ? 'bg-white text-[#1295D8] shadow-xs' : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                Side-by-Side View
              </button>
              <button
                type="button"
                onClick={() => {
                  setActiveTab('front');
                  setIsFlipped(false);
                }}
                className={`rounded-md px-3 py-1.5 transition-colors ${
                  activeTab === 'front' && !isFlipped ? 'bg-white text-[#1295D8] shadow-xs' : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                Front Side
              </button>
              <button
                type="button"
                onClick={() => {
                  setActiveTab('back');
                  setIsFlipped(true);
                }}
                className={`rounded-md px-3 py-1.5 transition-colors ${
                  activeTab === 'back' || isFlipped ? 'bg-white text-[#1295D8] shadow-xs' : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                Back Side
              </button>
            </div>

            <button
              type="button"
              onClick={() => setIsFlipped(!isFlipped)}
              className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 hover:bg-gray-50 md:hidden"
            >
              <RotateCw size={14} /> Flip Card
            </button>
          </div>
        </div>

        {/* ── Print Header Notice (Visible ONLY on Print) ── */}
        <div className="hidden print:block mb-4 text-center">
          <p className="text-[10px] font-black uppercase tracking-widest text-[#1A2B4A]">
            Gnosis Kaksha — Official Faculty Identity Card (Session 2026–2027)
          </p>
          <p className="text-[8px] text-gray-500 mt-0.5">
            ✂️ Cut along outer dashed lines • Insert back-to-back into standard PVC badge holder (85.6mm × 54mm)
          </p>
        </div>

        {/* ── Cards Container ── */}
        <div
          id="teacher-id-card-sheet"
          className="flex flex-col items-center justify-center gap-8 lg:flex-row lg:items-start lg:gap-10 print:flex print:flex-row print:items-start print:justify-center print:gap-8 print:m-0 print:p-0"
        >
          {/* ════════════════════════════════════════════
              TEACHER CARD: FRONT SIDE
              ════════════════════════════════════════════ */}
          {(activeTab === 'both' || activeTab === 'front' || !isFlipped) && (
            <div
              className={`id-card-element relative w-[340px] shrink-0 rounded-2xl overflow-hidden border border-gray-200 bg-white shadow-xl transition-all duration-300 print:w-[85.6mm] print:h-[135mm] print:rounded-xl print:shadow-none print:border-2 print:border-dashed print:border-gray-400 ${
                activeTab === 'back' ? 'hidden md:block' : ''
              }`}
            >
              {/* Lanyard punch hole aesthetic */}
              <div className="absolute top-2 left-1/2 -translate-x-1/2 w-10 h-2 rounded-full bg-gray-200/80 border border-gray-300/60 z-20 print:hidden" />

              {/* Watermark Logo */}
              <div className="absolute inset-0 flex items-center justify-center opacity-[0.03] pointer-events-none select-none z-0">
                <span className="text-[140px] font-black text-[#1A2B4A] rotate-[-25deg]">
                  GK
                </span>
              </div>

              {/* ── Header: Logo + Institute Name + Tagline + Address ── */}
              <div className="relative z-10 bg-gradient-to-br from-[#0F172A] via-[#1E293B] to-[#1E3A8A] px-4 pt-4 pb-3 text-white">
                <div className="flex items-center gap-3">
                  <div className="relative h-12 w-12 shrink-0 rounded-xl bg-white p-1 shadow-md border border-white/40 flex items-center justify-center overflow-hidden">
                    <Image
                      src="/logo.png"
                      alt="Gnosis Kaksha"
                      width={44}
                      height={44}
                      className="object-contain"
                      priority
                    />
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between">
                      <h3 className="font-black text-sm tracking-wider text-white leading-tight">
                        GNOSIS KAKSHA
                      </h3>
                      <span className="rounded bg-amber-400 px-1.5 py-0.5 text-[8px] font-black tracking-wide text-[#0F172A] shadow-xs uppercase">
                        FACULTY
                      </span>
                    </div>
                    <p className="text-[8.5px] font-extrabold tracking-widest text-amber-300 leading-tight mt-0.5 uppercase">
                      “A PLACE FOR EXCELLENCE”
                    </p>
                    <p className="text-[7.5px] text-slate-300 leading-tight mt-0.5 truncate">
                      Ramkrishna Nagar, Karimganj, Assam – 788713
                    </p>
                  </div>
                </div>
              </div>

              {/* Gold Accent Divider Bar */}
              <div className="h-[3.5px] bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500 shadow-xs" />

              {/* ── Body: Photo + Faculty Information ── */}
              <div className="relative z-10 bg-gradient-to-b from-white to-[#F8FAFC] p-4">
                <div className="flex gap-3.5 items-start">
                  {/* Photo Column */}
                  <div className="flex flex-col items-center gap-1.5 shrink-0">
                    <div className="relative h-[112px] w-[90px] rounded-lg border-2 border-[#1E3A8A] bg-blue-50/60 p-0.5 shadow-sm overflow-hidden flex flex-col items-center justify-center">
                      <div className="flex flex-col items-center justify-center text-[#1E3A8A]">
                        <User size={40} strokeWidth={1.5} />
                        <span className="mt-1 text-[8px] font-extrabold tracking-widest text-slate-500">
                          PHOTO
                        </span>
                      </div>
                    </div>
                    <span className="inline-block rounded-full bg-[#1E293B] px-2.5 py-0.5 text-[8px] font-black text-amber-300 shadow-xs tracking-wider">
                      {teacher.employeeId}
                    </span>
                  </div>

                  {/* Details Column */}
                  <div className="flex-1 min-w-0 space-y-1.5 text-left">
                    <div>
                      <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                        Faculty Name
                      </p>
                      <p className="text-[13px] font-black text-[#0F172A] leading-tight truncate mt-0.5">
                        {teacher.fullName}
                      </p>
                    </div>

                    <div>
                      <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                        Designation / Role
                      </p>
                      <p className="text-[10px] font-bold text-[#1295D8] leading-tight mt-0.5 line-clamp-2">
                        {teacher.designation}
                      </p>
                    </div>

                    <div>
                      <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                        Email
                      </p>
                      <p className="text-[9.5px] font-semibold text-slate-800 leading-tight truncate mt-0.5">
                        {teacher.email}
                      </p>
                    </div>

                  </div>
                </div>

                {/* ── Faculty Security Badge Strip ── */}
                <div className="mt-3 flex items-center justify-between rounded-lg bg-blue-50/90 border border-blue-200 px-2.5 py-1.5 shadow-2xs">
                  <div className="flex items-center gap-1.5">
                    <ShieldCheck size={14} className="text-[#1295D8] shrink-0" />
                    <span className="text-[8.5px] font-extrabold uppercase tracking-wide text-[#1E3A8A]">
                      Verified Faculty Member • 2026–2027
                    </span>
                  </div>
                  <span className="rounded-full bg-[#1295D8] px-1.5 py-0.2 text-[7px] font-bold text-white uppercase">
                    Staff
                  </span>
                </div>
              </div>

              {/* Gold Divider */}
              <div className="h-[2px] bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500" />

              {/* ── Barcode Strip ── */}
              <div className="relative z-10 bg-white px-4 py-2 text-center border-b border-gray-100">
                <TeacherBarcode value={teacher.employeeId} />
              </div>

              {/* ── Footer: Authorized Signatory & Dynamic QR Code ── */}
              <div className="relative z-10 bg-gradient-to-b from-[#F8FAFC] to-[#EFF6FF] px-4 py-2.5 flex items-end justify-between border-t border-slate-100">
                <div className="flex flex-col items-center">
                  <DirectorSignature />
                  <div className="border-t border-slate-400 pt-0.5 w-28 text-center mt-0.5">
                    <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-700 leading-none">
                      Authorized Signatory
                    </p>
                    <p className="text-[6.5px] font-medium text-slate-500 leading-none mt-0.5">
                      Director, Gnosis Kaksha
                    </p>
                  </div>
                </div>

                <div className="flex flex-col items-center gap-0.5">
                  <div className="rounded-md border border-slate-300 bg-white p-1 shadow-2xs">
                    <QRCodeSVG
                      value={`https://gnosiskaksha.cloud/verify/staff/${teacher.employeeId}`}
                      size={48}
                      level="M"
                      fgColor="#0F172A"
                    />
                  </div>
                  <span className="text-[6.5px] font-semibold text-slate-500 uppercase tracking-tighter">
                    Verify Staff
                  </span>
                </div>
              </div>

              {/* ── Bottom Strip ── */}
              <div className="relative z-10 bg-[#0F172A] px-3 py-1 flex items-center justify-between text-[7.5px] text-slate-300">
                <span>web: www.gnosiskaksha.cloud</span>
                <span>helpline: {OFFICE_PHONE_DISPLAY}</span>
              </div>
            </div>
          )}

          {/* ════════════════════════════════════════════
              TEACHER CARD: BACK SIDE
              ════════════════════════════════════════════ */}
          {(activeTab === 'both' || activeTab === 'back' || isFlipped) && (
            <div
              className={`id-card-element relative w-[340px] shrink-0 rounded-2xl overflow-hidden border border-gray-200 bg-white shadow-xl transition-all duration-300 print:w-[85.6mm] print:h-[135mm] print:rounded-xl print:shadow-none print:border-2 print:border-dashed print:border-gray-400 ${
                activeTab === 'front' ? 'hidden md:block' : ''
              }`}
            >
              {/* Lanyard punch hole aesthetic */}
              <div className="absolute top-2 left-1/2 -translate-x-1/2 w-10 h-2 rounded-full bg-gray-200/80 border border-gray-300/60 z-20 print:hidden" />

              {/* ── Back Header ── */}
              <div className="relative z-10 bg-gradient-to-br from-[#0F172A] via-[#1E293B] to-[#1E3A8A] px-4 pt-4 pb-3 text-center text-white">
                <h4 className="font-black text-xs tracking-widest uppercase text-white">
                  TERMS OF EMPLOYMENT &amp; CONDUCT
                </h4>
                <p className="text-[8px] font-semibold text-sky-200 mt-0.5 tracking-wider">
                  GNOSIS KAKSHA • OFFICIAL FACULTY CARD
                </p>
              </div>

              {/* Gold Divider */}
              <div className="h-[3px] bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500" />

              {/* ── Faculty Guidelines ── */}
              <div className="relative z-10 bg-white p-3.5 space-y-1.5">
                {[
                  'This card is the official institutional property of Gnosis Kaksha and must be worn or carried within the campus.',
                  'This card serves as authorized faculty identification for academic batches, evaluations, and official meetings.',
                  'In case of card loss or damage, immediately notify the Administration Office for a reissue.',
                  'Faculty members are expected to uphold the highest standards of academic excellence and professional ethics.',
                ].map((rule, idx) => (
                  <div key={idx} className="flex items-start gap-2">
                    <span className="flex h-3.5 w-3.5 shrink-0 items-center justify-center rounded-full bg-[#1E3A8A] text-[7px] font-bold text-white shadow-2xs mt-0.5">
                      {idx + 1}
                    </span>
                    <p className="text-[8px] leading-tight text-slate-700">{rule}</p>
                  </div>
                ))}
              </div>

              {/* ── Emergency Box ── */}
              <div className="mx-3.5 mb-2.5 rounded-lg border border-red-200 bg-red-50/70 p-2 text-center shadow-2xs">
                <p className="text-[8px] font-bold text-red-900 leading-tight">
                  🚨 EMERGENCY MEDICAL &amp; CAMPUS CONTACT
                </p>
                <p className="text-[7.5px] font-semibold text-red-800 leading-tight mt-0.5">
                  Institute helpline: {OFFICE_PHONE_DISPLAY}
                </p>
                <p className="text-[7px] text-gray-600 leading-tight mt-0.5">
                  Main Road, Ramkrishna Nagar, Karimganj, Assam – 788713
                </p>
              </div>

              {/* ── Summary Strip ── */}
              <div className="bg-[#F8FAFC] border-t border-b border-slate-200 px-3.5 py-1.5">
                <div className="grid grid-cols-2 gap-x-2 gap-y-0.5 text-[7.5px]">
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Employee: </span>
                    <span className="font-bold text-[#0F172A]">{teacher.fullName}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-400 uppercase">ID: </span>
                    <span className="font-bold text-[#1295D8] font-mono">{teacher.employeeId}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Role: </span>
                    <span className="font-bold text-slate-800">{teacher.designation}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Valid: </span>
                    <span className="font-bold text-emerald-700">Till 31-Mar-2027</span>
                  </div>
                </div>
              </div>

              {/* ── Back Footer ── */}
              <div className="bg-[#0F172A] px-3.5 py-2 flex items-center justify-between text-[7.5px] text-slate-300">
                <span className="flex items-center gap-1">
                  <Calendar size={9} className="text-amber-400" /> Academic Year: 2026–2027
                </span>
                <span className="font-bold text-amber-400">Official Staff Credential</span>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════════
          FULL TEACHER EMPLOYMENT & PERSONAL INFORMATION (Hidden on Print)
          ════════════════════════════════════════════════════════════════ */}
      <div className="print:hidden space-y-6">
        {/* Profile Hero Card */}
        <div className="flex flex-col items-center gap-5 rounded-2xl border border-gray-200 bg-white p-6 shadow-xs sm:flex-row sm:items-center">
          <div className="relative h-24 w-24 shrink-0 rounded-2xl border-2 border-[#1295D8] bg-[#CDE6F7] p-1 shadow-xs overflow-hidden flex items-center justify-center">
            <User size={48} className="text-[#1295D8]" />
          </div>

          <div className="flex-1 text-center sm:text-left">
            <div className="flex flex-wrap items-center justify-center sm:justify-start gap-2">
              <h2 className="text-2xl font-black text-[#1A2B4A]">{teacher.fullName}</h2>
              <Badge tone="green">Active Staff</Badge>
              <Badge tone="blue">{teacher.employeeId}</Badge>
            </div>
            <p className="text-sm font-semibold text-[#1295D8] mt-1">{teacher.designation}</p>
            <p className="text-xs text-gray-500 mt-0.5">{teacher.email}</p>
          </div>
        </div>

        {/* Account Details */}
        <SectionCard title="Account Details">
          <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <ProfileItem label="Full Name" value={teacher.fullName} icon={<User size={16} />} />
            <ProfileItem label="Official Email" value={teacher.email} icon={<Mail size={16} />} />
            <ProfileItem label="Role" value={teacher.designation} icon={<Briefcase size={16} />} />
            <ProfileItem label="Staff ID" value={teacher.employeeId} icon={<ShieldCheck size={16} />} />
          </dl>
          <p className="mt-4 text-xs text-[#718096]">
            Employment and personal details (qualification, joining date, contact number, address) are not on file yet.
            Contact the administration office to have them added.
          </p>
        </SectionCard>
      </div>

      {/* ── Global Print Styles for Teacher ID Card ── */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 10mm 8mm;
          }

          *,
          *::before,
          *::after {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }

          html,
          body {
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
            height: auto !important;
          }

          nav,
          header,
          aside,
          footer,
          .print\\:hidden,
          button {
            display: none !important;
          }

          #teacher-id-card-sheet {
            display: flex !important;
            flex-direction: row !important;
            align-items: flex-start !important;
            justify-content: center !important;
            gap: 12mm !important;
            width: 100% !important;
            margin: 0 auto !important;
            padding-top: 5mm !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }

          .id-card-element {
            display: block !important;
            width: 85.6mm !important;
            max-width: 85.6mm !important;
            border: 1.5px dashed #94a3b8 !important;
            border-radius: 4mm !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
            box-shadow: none !important;
            background: #ffffff !important;
          }
        }
      `}</style>
    </div>
  );
}
