'use client';

import { useState } from 'react';
import Image from 'next/image';
import {
  User,
  Printer,
  ShieldCheck,
  MapPin,
  Calendar,
  RotateCw,
  Scissors,
  Sparkles,
  Info,
} from 'lucide-react';
import { SectionCard } from '@/components/dashboard/SectionCard';
import { Badge } from '@/components/dashboard/Badge';
import { Button } from '@/components/ui/Button';
import { formatDate } from '@/lib/student-data';
import { useStudentPortal } from '@/hooks/useStudentPortal';
import { LoadingState, ErrorState } from '@/components/dashboard/PageState';
import { QRCodeSVG } from 'qrcode.react';

/* ─── Field component for Profile Section ─── */
function ProfileField({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs font-semibold uppercase tracking-wider text-[#718096]">{label}</dt>
      <dd className="mt-0.5 text-sm font-medium text-[#1A2B4A]">{value}</dd>
    </div>
  );
}

/* ─── High-Contrast Code-128 Style Barcode ─── */
function Barcode({ value }: { value: string }) {
  const seed = value.split('').map((c) => c.charCodeAt(0));
  type Bar = { x: number; w: number; black: boolean };
  const bars: Bar[] = [];
  let cursor = 0;
  let i = 0;
  const targetWidth = 230;

  while (cursor < targetWidth) {
    const w = ((seed[i % seed.length] + i * 3) % 3) + 1.2;
    bars.push({ x: cursor, w: Math.min(w * 1.8, targetWidth - cursor), black: i % 2 === 0 });
    cursor += w * 1.8;
    i++;
  }

  return (
    <div className="flex flex-col items-center gap-1">
      <svg
        width="230"
        height="36"
        viewBox="0 0 230 36"
        xmlns="http://www.w3.org/2000/svg"
        className="w-full max-w-[230px] h-9"
      >
        {bars.map((b, idx) =>
          b.black ? (
            <rect key={idx} x={b.x} y={0} width={b.w} height={36} fill="#0F172A" />
          ) : null
        )}
      </svg>
      <span className="font-mono text-[9px] tracking-[0.25em] text-[#1A2B4A] font-bold">
        * {value} *
      </span>
    </div>
  );
}

/* ─── Autogenerated Cursive Signature ─── */
function AutoSignature() {
  return (
    <svg viewBox="0 0 150 44" xmlns="http://www.w3.org/2000/svg" className="w-32 h-10">
      <path
        d="M10 28 C24 10, 42 8, 56 22 C66 32, 74 12, 88 16 C102 20, 114 30, 126 22 C134 16, 142 24, 146 28"
        fill="none"
        stroke="#1E3A8A"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12 34 C45 32, 95 32, 144 34"
        fill="none"
        stroke="#1E3A8A"
        strokeWidth="0.8"
        strokeLinecap="round"
      />
      <circle cx="140" cy="22" r="1.5" fill="#1E3A8A" />
    </svg>
  );
}

/* ─── Official Rules & Regulations ─── */
const RULES = [
  'This card is the official property of Gnosis Kaksha and must be produced on demand inside the premises.',
  'This card is strictly non-transferable. Impersonation or misuse will lead to immediate disciplinary cancellation.',
  'Students must maintain at least 85% attendance across all enrolled subjects and attend all periodic tests.',
  'Mobile phones and gadgets must remain strictly switched off or in silent mode during class hours.',
  'Monthly tuition fees must be cleared on or before the 10th of every month to avoid late penalty.',
  'Strict disciplinary action including expulsion will be taken for ragging, harassment, or property damage.',
  'In case of card loss or damage, immediately notify the office. Duplicate card issue fee applies.',
  'Students must follow the designated batch timings and adhere to the institute code of conduct.',
];

export default function StudentProfilePage() {
  const { data, error, loading, reload } = useStudentPortal();
  const [activeTab, setActiveTab] = useState<'both' | 'front' | 'back'>('both');
  const [isFlipped, setIsFlipped] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  if (loading && !data) return <LoadingState label="Loading profile…" />;
  if (error) return <ErrorState message={error.message} onRetry={reload} />;
  if (!data) return null;
  const { profile } = data;

  return (
    <div className="space-y-8">
      {/* ── Page Header (Hidden on Print) ── */}
      <div className="flex flex-wrap items-center justify-between gap-4 print:hidden">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-3xl font-extrabold tracking-tight text-[#1A2B4A]">
              Student Profile &amp; ID Card
            </h1>
            <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-0.5 text-xs font-semibold text-[#1295D8] border border-blue-200">
              <Sparkles size={12} /> Official PVC Badge
            </span>
          </div>
          <p className="mt-1 text-sm text-[#4A5568]">
            Official institutional identity, academic enrollment, and printable two-sided student ID badge.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Button
            type="button"
            onClick={handlePrint}
            className="gap-2 bg-gradient-to-r from-[#1295D8] to-[#2E5EAA] text-white shadow-md hover:shadow-lg transition-all"
          >
            <Printer size={16} /> Print / Save ID Card (PDF)
          </Button>
        </div>
      </div>

      {/* ── Print Quality of Life Tip Banner (Hidden on Print) ── */}
      <div className="rounded-xl border border-blue-200 bg-gradient-to-r from-blue-50 to-indigo-50 p-4 shadow-xs print:hidden">
        <div className="flex items-start gap-3">
          <div className="rounded-lg bg-[#1295D8] p-2 text-white shadow-xs shrink-0">
            <Info size={18} />
          </div>
          <div className="flex-1 text-xs leading-relaxed text-[#2D3748]">
            <p className="font-bold text-[#1A2B4A] text-sm mb-0.5">
              Print &amp; PDF Instructions
            </p>
            When you click <strong>Print / Save ID Card</strong>, the page automatically formats into a ready-to-cut <strong>A4 Sheet</strong> with both Front &amp; Back side-by-side with cut guidelines.
            <span className="block mt-1 font-semibold text-[#1E3A8A]">
              💡 Tip: In your browser print dialog, make sure to check <u>&quot;Background graphics&quot;</u> so the rich navy colors, gold stripes, and badges print in full color!
            </span>
          </div>
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════════
          ID CARD SHOWCASE SECTION (Interactive on screen, Sheet on print)
          ════════════════════════════════════════════════════════════════ */}
      <div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm print:p-0 print:border-none print:shadow-none print:m-0">
        {/* Showcase Controls (Hidden on Print) */}
        <div className="mb-6 flex flex-wrap items-center justify-between gap-4 border-b border-gray-100 pb-4 print:hidden">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-[#1A2B4A]">Digital ID Card Preview</h2>
            <Badge tone="green">Verified 2026–2027</Badge>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <div className="inline-flex rounded-lg border border-gray-200 bg-gray-50 p-1 text-xs font-semibold">
              <button
                type="button"
                onClick={() => {
                  setActiveTab('both');
                  setIsFlipped(false);
                }}
                className={`rounded-md px-3 py-1.5 transition-colors ${
                  activeTab === 'both'
                    ? 'bg-white text-[#1295D8] shadow-xs'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                Side-by-Side View
              </button>
              <button
                type="button"
                onClick={() => {
                  setActiveTab('front');
                  setIsFlipped(false);
                }}
                className={`rounded-md px-3 py-1.5 transition-colors ${
                  activeTab === 'front' && !isFlipped
                    ? 'bg-white text-[#1295D8] shadow-xs'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                Front Side
              </button>
              <button
                type="button"
                onClick={() => {
                  setActiveTab('back');
                  setIsFlipped(true);
                }}
                className={`rounded-md px-3 py-1.5 transition-colors ${
                  activeTab === 'back' || isFlipped
                    ? 'bg-white text-[#1295D8] shadow-xs'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                Back Side
              </button>
            </div>

            <button
              type="button"
              onClick={() => setIsFlipped(!isFlipped)}
              className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-semibold text-gray-700 hover:bg-gray-50 md:hidden"
            >
              <RotateCw size={14} /> Flip Card
            </button>
          </div>
        </div>

        {/* ── Print Header Notice (Visible ONLY on Print) ── */}
        <div className="hidden print:block mb-4 text-center">
          <p className="text-[10px] font-black uppercase tracking-widest text-[#1A2B4A]">
            Gnosis Kaksha — Official Student Identity Card Sheet (Session 2026–2027)
          </p>
          <p className="text-[8px] text-gray-500 mt-0.5">
            ✂️ Cut along outer dashed lines • Insert back-to-back or fold at center for standard PVC ID card holder (85.6mm × 54mm)
          </p>
        </div>

        {/* ── Card Container (Responsive Grid / Print Sheet) ── */}
        <div
          id="id-card-printable-area"
          className="flex flex-col items-center justify-center gap-8 lg:flex-row lg:items-start lg:gap-10 print:flex print:flex-row print:items-start print:justify-center print:gap-8 print:m-0 print:p-0"
        >
          {/* ══════════════════════════════════
              CARD FRONT SIDE
              ══════════════════════════════════ */}
          {(activeTab === 'both' || activeTab === 'front' || !isFlipped) && (
            <div
              className={`id-card-element relative w-[340px] shrink-0 rounded-2xl overflow-hidden border border-gray-200 bg-white shadow-xl transition-all duration-300 print:w-[85.6mm] print:h-[135mm] print:rounded-xl print:shadow-none print:border-2 print:border-dashed print:border-gray-400 ${
                activeTab === 'back' ? 'hidden md:block' : ''
              }`}
            >
              {/* Lanyard punch hole aesthetic (screen only) */}
              <div className="absolute top-2 left-1/2 -translate-x-1/2 w-10 h-2 rounded-full bg-gray-200/80 border border-gray-300/60 z-20 print:hidden" />

              {/* Watermark Logo Background */}
              <div className="absolute inset-0 flex items-center justify-center opacity-[0.03] pointer-events-none select-none z-0">
                <span className="text-[140px] font-black text-[#1A2B4A] rotate-[-25deg]">
                  GK
                </span>
              </div>

              {/* ── Header: Logo + Institute Name + Tagline + Address ── */}
              <div className="relative z-10 bg-gradient-to-br from-[#0F172A] via-[#1E293B] to-[#1E3A8A] px-4 pt-4 pb-3 text-white">
                <div className="flex items-center gap-3">
                  {/* Official Logo */}
                  <div className="relative h-12 w-12 shrink-0 rounded-xl bg-white p-1 shadow-md border border-white/40 flex items-center justify-center overflow-hidden">
                    <Image
                      src="/logo.png"
                      alt="Gnosis Kaksha"
                      width={44}
                      height={44}
                      className="object-contain"
                      priority
                    />
                  </div>

                  {/* Text Header */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between">
                      <h3 className="font-black text-sm tracking-wider text-white leading-tight">
                        GNOSIS KAKSHA
                      </h3>
                      <span className="rounded bg-amber-400 px-1.5 py-0.5 text-[8px] font-black tracking-wide text-[#0F172A] shadow-xs uppercase">
                        2026–27
                      </span>
                    </div>
                    <p className="text-[8.5px] font-semibold text-sky-200 leading-tight mt-0.5">
                      Premier Coaching &amp; Academic Excellence
                    </p>
                    <p className="text-[7.5px] text-slate-300 leading-tight mt-0.5 flex items-center gap-0.5 truncate">
                      <MapPin size={8} className="shrink-0 text-amber-400" />
                      Ramkrishna Nagar, Karimganj, Assam – 788713
                    </p>
                  </div>
                </div>
              </div>

              {/* Gold Accent Divider Bar */}
              <div className="h-[3.5px] bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500 shadow-xs" />

              {/* ── Body: Photo + Student Information ── */}
              <div className="relative z-10 bg-gradient-to-b from-white to-[#F8FAFC] p-4">
                <div className="flex gap-3.5 items-start">
                  {/* Student Photo Column */}
                  <div className="flex flex-col items-center gap-1.5 shrink-0">
                    <div className="relative h-[112px] w-[90px] rounded-lg border-2 border-[#1295D8] bg-blue-50/60 p-0.5 shadow-sm overflow-hidden flex flex-col items-center justify-center">
                      {profile.photoUrl ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={profile.photoUrl}
                          alt={profile.fullName}
                          className="h-full w-full object-cover rounded-md"
                        />
                      ) : (
                        <div className="flex flex-col items-center justify-center text-[#1295D8]">
                          <User size={40} strokeWidth={1.5} />
                          <span className="mt-1 text-[8px] font-extrabold tracking-widest text-slate-500">
                            PHOTO
                          </span>
                        </div>
                      )}
                      {/* Gloss sheen */}
                      <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/10 to-white/40 pointer-events-none" />
                    </div>

                    {/* Class Badge */}
                    <span className="inline-block rounded-full bg-[#1E293B] px-2.5 py-0.5 text-[8.5px] font-black text-amber-300 shadow-xs tracking-wider">
                      CLASS {profile.classNumber} {profile.board ? `• ${profile.board}` : ''}
                    </span>
                  </div>

                  {/* Student Details Column */}
                  <div className="flex-1 min-w-0 space-y-1.5 text-left">
                    <div>
                      <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                        Student Name
                      </p>
                      <p className="text-[13px] font-black text-[#0F172A] leading-tight truncate mt-0.5">
                        {profile.fullName}
                      </p>
                    </div>

                    <div>
                      <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                        Registration No.
                      </p>
                      <p className="font-mono text-[11px] font-bold text-[#1295D8] leading-tight mt-0.5">
                        {profile.registrationNumber}
                      </p>
                    </div>

                    <div className="grid grid-cols-1 gap-1">
                      <div>
                        <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                          Father&apos;s / Guardian Name
                        </p>
                        <p className="text-[10px] font-semibold text-slate-800 leading-tight truncate mt-0.5">
                          {profile.parentName || '—'}
                        </p>
                      </div>

                      <div>
                        <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                          Contact Number
                        </p>
                        <p className="text-[10px] font-bold text-slate-800 leading-tight mt-0.5">
                          +91 {profile.mobile}
                        </p>
                      </div>

                      <div>
                        <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-400 leading-none">
                          Permanent Address
                        </p>
                        <p className="text-[9px] font-medium text-slate-600 leading-tight line-clamp-2 mt-0.5">
                          {profile.address || '—'}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* ── Security Verified Badge Strip ── */}
                <div className="mt-3 flex items-center justify-between rounded-lg bg-emerald-50/90 border border-emerald-200 px-2.5 py-1.5 shadow-2xs">
                  <div className="flex items-center gap-1.5">
                    <ShieldCheck size={14} className="text-emerald-600 shrink-0" />
                    <span className="text-[8.5px] font-extrabold uppercase tracking-wide text-emerald-800">
                      Verified Active Student • 2026–2027
                    </span>
                  </div>
                  <span className="rounded-full bg-emerald-600 px-1.5 py-0.2 text-[7px] font-bold text-white uppercase">
                    Valid
                  </span>
                </div>
              </div>

              {/* Gold Accent Divider Bar */}
              <div className="h-[2px] bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500" />

              {/* ── Barcode Strip ── */}
              <div className="relative z-10 bg-white px-4 py-2 text-center border-b border-gray-100">
                <Barcode value={profile.registrationNumber} />
              </div>

              {/* ── Footer: Authorized Signatory & Dynamic QR Code ── */}
              <div className="relative z-10 bg-gradient-to-b from-[#F8FAFC] to-[#EFF6FF] px-4 py-2.5 flex items-end justify-between border-t border-slate-100">
                {/* Authorized Signatory */}
                <div className="flex flex-col items-center">
                  <AutoSignature />
                  <div className="border-t border-slate-400 pt-0.5 w-28 text-center mt-0.5">
                    <p className="text-[7.5px] font-bold uppercase tracking-wider text-slate-700 leading-none">
                      Authorized Signatory
                    </p>
                    <p className="text-[6.5px] font-medium text-slate-500 leading-none mt-0.5">
                      Director, Gnosis Kaksha
                    </p>
                  </div>
                </div>

                {/* QR Code Verification */}
                <div className="flex flex-col items-center gap-0.5">
                  <div className="rounded-md border border-slate-300 bg-white p-1 shadow-2xs">
                    <QRCodeSVG
                      value={`https://gnosiskaksha.cloud/verify/${profile.registrationNumber}`}
                      size={48}
                      level="M"
                      fgColor="#0F172A"
                    />
                  </div>
                  <span className="text-[6.5px] font-semibold text-slate-500 uppercase tracking-tighter">
                    Scan to Verify
                  </span>
                </div>
              </div>

              {/* ── Bottom Strip ── */}
              <div className="relative z-10 bg-[#0F172A] px-3 py-1 flex items-center justify-between text-[7.5px] text-slate-300">
                <span>web: gnosiskaksha.cloud</span>
                <span>helpline: +91 84740 20124</span>
              </div>
            </div>
          )}

          {/* ══════════════════════════════════
              CARD BACK SIDE (Rules & Regulations)
              ══════════════════════════════════ */}
          {(activeTab === 'both' || activeTab === 'back' || isFlipped) && (
            <div
              className={`id-card-element relative w-[340px] shrink-0 rounded-2xl overflow-hidden border border-gray-200 bg-white shadow-xl transition-all duration-300 print:w-[85.6mm] print:h-[135mm] print:rounded-xl print:shadow-none print:border-2 print:border-dashed print:border-gray-400 ${
                activeTab === 'front' ? 'hidden md:block' : ''
              }`}
            >
              {/* Lanyard punch hole aesthetic (screen only) */}
              <div className="absolute top-2 left-1/2 -translate-x-1/2 w-10 h-2 rounded-full bg-gray-200/80 border border-gray-300/60 z-20 print:hidden" />

              {/* ── Back Header ── */}
              <div className="relative z-10 bg-gradient-to-br from-[#0F172A] via-[#1E293B] to-[#1E3A8A] px-4 pt-4 pb-3 text-center text-white">
                <h4 className="font-black text-xs tracking-widest uppercase text-white">
                  RULES &amp; CODE OF CONDUCT
                </h4>
                <p className="text-[8px] font-semibold text-sky-200 mt-0.5 tracking-wider">
                  GNOSIS KAKSHA • STUDENT IDENTITY CARD
                </p>
              </div>

              {/* Gold Divider */}
              <div className="h-[3px] bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500" />

              {/* ── Rules List ── */}
              <div className="relative z-10 bg-white p-3.5 space-y-1.5">
                {RULES.map((rule, idx) => (
                  <div key={idx} className="flex items-start gap-2">
                    <span className="flex h-3.5 w-3.5 shrink-0 items-center justify-center rounded-full bg-[#1295D8] text-[7px] font-bold text-white shadow-2xs mt-0.5">
                      {idx + 1}
                    </span>
                    <p className="text-[8px] leading-tight text-slate-700">
                      {rule}
                    </p>
                  </div>
                ))}
              </div>

              {/* ── If Lost / Emergency Box ── */}
              <div className="mx-3.5 mb-2.5 rounded-lg border border-amber-300 bg-amber-50/90 p-2 text-center shadow-2xs">
                <p className="text-[8px] font-bold text-amber-900 leading-tight">
                  ⚠️ If found, please return this card to:
                </p>
                <p className="text-[7.5px] font-semibold text-amber-800 leading-tight mt-0.5">
                  Gnosis Kaksha, Main Road, Ramkrishna Nagar, Karimganj, Assam – 788713
                </p>
                <p className="text-[7px] text-amber-700 leading-tight mt-0.5 font-mono">
                  Phone: +91 84740 20124 • Email: query@gnosiskaksha.in
                </p>
              </div>

              {/* ── Student Verification Summary Strip ── */}
              <div className="bg-[#F8FAFC] border-t border-b border-slate-200 px-3.5 py-1.5">
                <div className="grid grid-cols-2 gap-x-2 gap-y-0.5 text-[7.5px]">
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Student: </span>
                    <span className="font-bold text-[#0F172A]">{profile.fullName}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Reg No: </span>
                    <span className="font-bold text-[#1295D8] font-mono">{profile.registrationNumber}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Class: </span>
                    <span className="font-bold text-slate-800">Class {profile.classNumber}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-400 uppercase">Valid: </span>
                    <span className="font-bold text-emerald-700">Till 31-Mar-2027</span>
                  </div>
                </div>
              </div>

              {/* ── Back Footer ── */}
              <div className="bg-[#0F172A] px-3.5 py-2 flex items-center justify-between text-[7.5px] text-slate-300">
                <span className="flex items-center gap-1">
                  <Calendar size={9} className="text-amber-400" /> Session: 2026–2027
                </span>
                <span className="font-bold text-amber-400">
                  Official Academic Document
                </span>
              </div>
            </div>
          )}
        </div>

        {/* Action button bar under cards (Hidden on Print) */}
        <div className="mt-6 flex flex-wrap items-center justify-center gap-4 print:hidden">
          <Button
            type="button"
            onClick={handlePrint}
            className="gap-2 bg-[#1A2B4A] hover:bg-[#1295D8] text-white shadow-sm"
          >
            <Printer size={15} /> Print ID Card (Both Sides)
          </Button>

          <span className="text-xs text-gray-500 flex items-center gap-1">
            <Scissors size={14} className="text-gray-400" /> Ready to print on A4 sheet with cut guidelines
          </span>
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════════
          FULL PROFILE DETAILS (Academic, Guardian & Registration Info)
          ════════════════════════════════════════════════════════════════ */}
      <div className="print:hidden space-y-6">
        {/* Quick Identity Summary Banner */}
        <div className="flex flex-col items-center gap-4 rounded-xl border border-gray-200 bg-white p-6 shadow-sm sm:flex-row sm:items-center">
          <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-full bg-[#CDE6F7] text-[#1295D8] border-2 border-white shadow-sm">
            <User size={40} />
          </div>
          <div className="flex-1 text-center sm:text-left">
            <div className="flex flex-wrap items-center justify-center sm:justify-start gap-2">
              <h2 className="text-2xl font-bold text-[#1A2B4A]">{profile.fullName}</h2>
              <Badge tone="green">Active Enrolled</Badge>
              <Badge tone="blue">Class {profile.classNumber}</Badge>
            </div>
            <p className="font-mono text-sm font-semibold text-[#1295D8] mt-1">
              Registration No: {profile.registrationNumber}
            </p>
            <div className="mt-2 flex flex-wrap justify-center gap-2 sm:justify-start">
              {profile.stream && <Badge tone="gray">{profile.stream}</Badge>}
              <Badge tone="gray">{profile.board} Board</Badge>
              <span className="text-xs text-gray-500 self-center">
                Admitted on: {formatDate(profile.admissionDate)}
              </span>
            </div>
          </div>
        </div>

        {/* Detailed Grid: Academic & Guardian Information */}
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          <SectionCard title="Academic & Enrollment Details">
            <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <ProfileField label="Full Name" value={profile.fullName} />
              <ProfileField label="Registration Number" value={profile.registrationNumber} />
              <ProfileField label="Class Level" value={`Class ${profile.classNumber}`} />
              <ProfileField label="Stream / Course" value={profile.stream ?? 'General'} />
              <ProfileField label="Academic Board" value={profile.board} />
              <ProfileField label="Admission Date" value={formatDate(profile.admissionDate)} />
            </dl>
          </SectionCard>

          <SectionCard title="Contact & Guardian Information">
            <dl className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <ProfileField label="Student Mobile" value={profile.mobile} />
              <ProfileField label="Student Email" value={profile.email} />
              <ProfileField label="Father / Guardian" value={profile.parentName} />
              <ProfileField label="Emergency Contact" value={profile.guardianMobile} />
              <div className="sm:col-span-2">
                <ProfileField label="Permanent Residential Address" value={profile.address} />
              </div>
            </dl>
          </SectionCard>
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════════
          PRINT STYLES: Enforces 1-Page A4 Sheet, Exact Backgrounds & No Blank Pages
          ════════════════════════════════════════════════════════════════ */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4 portrait;
            margin: 10mm 8mm;
          }

          /* Force exact backgrounds and colors across all browsers */
          *,
          *::before,
          *::after {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }

          html,
          body {
            background: #ffffff !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
            height: auto !important;
          }

          /* Hide all non-printable dashboard elements */
          nav,
          header,
          aside,
          footer,
          .print\\:hidden,
          button,
          [role="navigation"] {
            display: none !important;
          }

          /* Printable container styling */
          #id-card-printable-area {
            display: flex !important;
            flex-direction: row !important;
            align-items: flex-start !important;
            justify-content: center !important;
            gap: 12mm !important;
            width: 100% !important;
            margin: 0 auto !important;
            padding-top: 5mm !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }

          .id-card-element {
            display: block !important;
            width: 85.6mm !important;
            max-width: 85.6mm !important;
            border: 1.5px dashed #94a3b8 !important;
            border-radius: 4mm !important;
            overflow: hidden !important;
            page-break-inside: avoid !important;
            break-inside: avoid !important;
            box-shadow: none !important;
            background: #ffffff !important;
          }
        }
      `}</style>
    </div>
  );
}
